quarkus:
  banner:
    enabled: false
  hibernate-orm:
    database:
      generation: none
  quinoa:
    enable-spa-routing: true
    build-dir: dist/example-ng/browser

mp:
  openapi:
    extensions:
      smallrye:
        info:
          title: OD2T API
          version: 0.0.1
          description: API for OD2T
          contact:
            email: techsupport@redhat.com
            name: OD2T API Support
            url: https://github.com/quarkus-ground-up/customer-api
          license:
            name: Apache 2.0
            url: http://www.apache.org/licenses/LICENSE-2.0.html
